version: '3.4'
services:
  nginx:
    image: nginx:1.13
    container_name: sns_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/project/static:/static
      - ./nginx/log:/var/log/nginx
    depends_on:
      - python
  db:
    image: mariadb:10.1
    container_name: sns_mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sns
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
  python:
    build: ./python
    image: sns_python
    container_name: sns_python
    expose:
      - "8001"
    ports:
      - "8001:8001"
    command: uwsgi --ini /code/uwsgi.ini
    volumes:
      - ./src/project:/code
    depends_on:
      - db