# Generated by Django 3.0 on 2019-12-20 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.CharField(max_length=100)),
                ('images', models.ImageField(height_field='url_height', upload_to='', width_field='url_width')),
                ('like', models.IntegerField(default=0, verbose_name='like')),
                ('read', models.IntegerField(default=0, verbose_name='read')),
                ('readtxt', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
        ),
    ]
