# Generated by Django 3.0 on 2019-12-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
