# Generated by Django 3.0 on 2019-12-20 12:19

from django.db import migrations, models
import sns.models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20191220_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(upload_to=sns.models.image_post_directory_path),
        ),
    ]
